# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(max_length=200, unique=True, verbose_name='Badge ID')),
                ('badge_level', models.IntegerField(verbose_name='Badge Level')),
                ('badge_nick', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Badge Alias')),
                ('badge_salt', models.CharField(max_length=200, verbose_name='Badge Salt')),
                ('badge_status', models.CharField(default='noob', max_length=200, verbose_name='Badge Status')),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=200, unique=True, verbose_name='Challenge Name')),
                ('challenge_description', models.TextField(verbose_name='Challenge Description')),
                ('challenge_pass', models.CharField(max_length=200, unique=True, verbose_name='Challenge Password')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200, unique=True, verbose_name='Team Name')),
                ('team_binary', models.IntegerField(unique=True, verbose_name='Team LED Int')),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_challenges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='badge.Challenges'),
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='badge.Team'),
        ),
    ]
