# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='badge_challenges',
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_challenges',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, to='badge.Challenges'),
        ),
    ]
