# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-07 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_auto_20161031_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_challenges',
            field=models.ManyToManyField(blank=True, to='badge.Challenges'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_nick',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Badge Alias'),
        ),
    ]
