# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0006_auto_20161107_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_verify',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Badge Verify Code'),
        ),
    ]
