# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-12 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0007_badge_badge_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='challenge_valid',
            field=models.CharField(default='complete', max_length=200, verbose_name='Challenge Valid Code'),
        ),
    ]
