# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0008_challenges_challenge_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_verify',
            field=models.CharField(max_length=200, null=True, verbose_name='Badge Verify Code'),
        ),
    ]
