# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0009_auto_20161113_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Log TimeStamp')),
                ('log_type', models.CharField(max_length=200, verbose_name='Log Type')),
                ('log_description', models.CharField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_lastseen',
            field=models.DateTimeField(null=True, verbose_name='Badge Lastseen'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_badgeOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeOne', to='badge.Badge'),
        ),
        migrations.AddField(
            model_name='log',
            name='log_badgeTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeTwo', to='badge.Badge'),
        ),
    ]
