# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0010_auto_20161118_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_badgeTwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badgeTwo', to='badge.Badge'),
        ),
    ]
