# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0011_auto_20161118_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_badgesSeen',
            field=models.ManyToManyField(blank=True, null=True, to='badge.Badge'),
        ),
    ]
