# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-29 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0012_badge_badge_badgesseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamestatus_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Log TimeStamp')),
                ('gamestatus_red', models.IntegerField(verbose_name='Number of Red Players')),
                ('gamestatus_green', models.IntegerField(verbose_name='Number of Green Players')),
                ('gamestatus_blue', models.IntegerField(verbose_name='Number of Blue Players')),
            ],
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_badgesSeen',
            field=models.ManyToManyField(blank=True, to='badge.Badge'),
        ),
    ]
