# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-01 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0013_auto_20161129_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPSSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpssl_timestamp', models.DateTimeField(verbose_name='RPSSL TimeStamp')),
                ('rpssl_pick1', models.CharField(max_length=200, null=True, verbose_name='Badge One Pick')),
                ('rpssl_pick2', models.CharField(max_length=200, null=True, verbose_name='Badge Two Pick')),
                ('rpssl_badgeOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpssl_badgeOne', to='badge.Badge')),
                ('rpssl_badgeTwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rpssl_badgeTwo', to='badge.Badge')),
            ],
        ),
    ]
