# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-01 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0015_rpssl_rpssl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpssl',
            name='rpssl_badgesConfirmed',
            field=models.IntegerField(default=0, verbose_name='Game Confirmed by both players'),
        ),
        migrations.AlterField(
            model_name='rpssl',
            name='rpssl_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='RPSSL TimeStamp'),
        ),
    ]
