# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-01 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0016_auto_20161201_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpssl',
            name='rpssl_pick1',
            field=models.IntegerField(default=-1, verbose_name='Badge One Pick'),
        ),
        migrations.AlterField(
            model_name='rpssl',
            name='rpssl_pick2',
            field=models.IntegerField(default=-1, verbose_name='Badge Two Pick'),
        ),
    ]
