# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-02 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0018_badge_badge_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_message',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Badge Message'),
        ),
    ]
